# Generated by Django 3.0.3 on 2020-08-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('residence_state', models.CharField(max_length=2)),
                ('security_code', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
