# Generated by Django 3.0.3 on 2020-08-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('godkids', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kids',
            new_name='Kid',
        ),
    ]
